config/routes.rb
Angeltation::Application.routes.draw do

resources :emails 
resources :legends do 
 resources :books 
end 

	root "static_pages#Home"
	match "/about", to: "static_pages#About", via: 'get' 
	match "/how", to: "static_pages#How", via: 'get' 
	match "/contact", to: "static_pages#Contact", via: 'get' 
	match "/privacy", to: "static_pages#Privacy", via: 'get' 
	match "/terms", to: "static_pages#Terms", via: 'get' 
	match "/admin", to: "legends#index", via: 'get'
	match "/user_email", to: "static_pages#user_email", via: 'get'
end

app/models/book.rb
class Book < ActiveRecord::Base

validates :title, :image, :link, :legend_id, presence: true 

belongs_to :legend

end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/legend.rb
class Legend < ActiveRecord::Base

validates :name, :image, presence: true 

has_many :books, dependent: :destroy  


def to_param	
	"#{id} #{name}".parameterize	
end
# this code overrides the to_params method that convert a model into a url. 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
http_basic_authenticate_with :name => "Admin", :password => "Rothgordt1", only: [:index, :new, :edit]

  def index
    @legend = Legend.find(params[:legend_id])
    @books = @legend.books
  end

  def show
  end

  def new
    @legend = Legend.find(params[:legend_id])
    @book = @legend.books.build
  end

  def create
      @legend = Legend.find(params[:legend_id])
      @book = @legend.books.create(book_params)
      if @book.save
        flash[:success] = "New book has been added"
        redirect_to new_legend_book_path(@legend)
      else  
        flash[:error] = "EPIC FAIL"
        redirect_to root_path 
      end 
  end

  def edit
    @legend = Legend.find(params[:legend_id])
    @book = Book.find(params[:id])
  end

  def update
    @legend = Legend.find(params[:legend_id])
    @book = @legend.books.find(params[:id])
    @book.update(book_params)
    redirect_to legend_books_path(@legend, @book)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy 
    flash[:notice] = "Book destroyed"
    redirect_to root_path
  end
end

    private 

    def book_params 
      params.require(:book).permit(:title, :description, :image, :link, :legend_id)
    end 

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
  	@email = Email.new(email_params)
  	if @email.save 
  		flash[:success] = "Your email has been sent. Thank you for your input. We'll take care of it ASAP."
      UserMailer.user_input(@email).deliver
      # Call the mailer, call the relevant method. Then call deliver. 
      redirect_to root_path
  	else 
  	 	flash[:error] = "FAILure."
  		redirect_to root_path
  	end	
  end

  private

  def email_params 
  	params.require(:email).permit(:email)
  end 	
end

app/controllers/legends_controller.rb
class LegendsController < ApplicationController
http_basic_authenticate_with :name => "Admin", :password => "Rothgordt1", only: [:index, :new, :edit]

  def index
    @legends = Legend.all 
  end

  def show
    @legend = Legend.find(params[:id])
    @books = @legend.books.order('random()')
    @legends = Legend.order('random()').page(params[:page]).per_page(4)
    # this way of paginating retrieves the objects form the database in random order. 
  end

  def new
    @legend = Legend.new 
  end

  def create
    @legend = Legend.new(legend_params)
    if @legend.save 
      flash[:success] = "A new legend has been successfully introduced."
      redirect_to root_path 
    else 
      flash[:error] = "Epic Fail"
      redirect_to root_path
    end 
  end

  def edit
    @legend = Legend.find(params[:id])
  end

  def update
    @legend = Legend.find(params[:id])
    @legend.update(legend_params)
    redirect_to root_path
  end

  def destroy
    @legend = Legend.find(params[:id])
    @legend.destroy 
    redirect_to root_path
  end

end


  private 

  def legend_params
    params.require(:legend).permit(:name, :description, :image)
  end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def Home
    @legends = Legend.order('random()').page(params[:page]).per_page(30)
  end

  def About
  end

  def How
  end

  def Contact
  end

  def Privacy
  end

  def Terms
  end

  def user_email
    @email = Email.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/legends_helper.rb
module LegendsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="row">
	<div class="span8 offset2 centered ">
		<div class="admin_form">

			<%= form_for([@legend,@book]) do |f| %> 

				<%= f.label :title %> 
				<%= f.text_field :title %> <br>

				<%= f.label :description %> 
				<%= f.text_area :description %> <br>

				<%= f.label :image, "Image-Link" %> 
				<%= f.text_field :image %> <br>

				<%= f.label :link, "Amazon-Link" %> 
				<%= f.text_field :link %> <br> <br>

				<%= f.submit "Submit", class: "btn btn-medium btn-warning" %>  

			<% end %> 
		
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="row"> 
	<div class="span10 offset1 centered"> 

		<h1> Books of <%= @legend.name %> </h1> 
		<h3> <%= link_to "Add another book to this reading list", new_legend_book_path %> </h3> 
		<br>

		<% @books.each do |book| %> 
			<div class="box legend_box">
				<a href="<%= book.link %>" target="_blank"> 
				<img src="<%= book.image %>" width="300" height="300" /> </a> 
				<h4> <%= link_to "Edit", edit_legend_book_path(@legend, book) %> </h4>
				<h4> <%= link_to "Destroy", legend_book_path(@legend, book), method: :delete, data: { confirm: "Delete? Really?" } %> </h4> <br>
			</div> 

		<% end %> 

	</div>
</div>

app/views/books/new.html.erb
<div class="row">
	<div class="span8 offset2 centered ">
		<div class="admin_form">

			<%= form_for([@legend,@book]) do |f| %> 

				<%= f.label :title %> 
				<%= f.text_field :title %> <br>

				<%= f.label :description %> 
				<%= f.text_area :description %> <br>

				<%= f.label :link, "Amazon-Link" %> 
				<%= f.text_field :link %> <br> <br>

				<%= f.label :image, "Image-Link" %> 
				<%= f.text_field :image %> <br> <br>

				<%= f.submit "Submit", class: "btn btn-medium btn-warning" %>  

			<% end %> 
	
		</div>
	</div>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47565884-1', 'readingranked.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="header nav-collapse collapse">
        <ul class="nav">
          <li> <%= link_to "ReadingRanked", root_path %>  </li>
          <li> <%= link_to "About", about_path %>  </li>
          <li> <%= link_to "Make a suggestion", user_email_path %>  </li>
        </ul> 

        <ul class="nav pull-right">
          <li> <%= link_to "Admin", admin_path %>  </li>
        </ul> 

      </div>

    </div>
  </div>
</div>

app/views/layouts/_legends.html.erb
<% @legends.each do |legend| %> 
	
		<div class="box">
			<a href="<%= legend_path(legend) %>">
			<img src= "<%= legend.image %>" width="320" height="240" /> </a>
			<h4> <%= legend.name %> </h4>
			<p> <%= legend.description %> </p>
			<h5> <%= link_to "Reading List", legend_path(legend) %> 
		</div>
	
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Readingranked | <%= yield(:tab_title) %> </title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>


	<body>
		<%= render "layouts/header" %> 	

		<div class="container">
			<% flash.each do |name, msg| %> 
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %> 
			<% end %>
			
			<%= yield %>

		<%= render "layouts/footer" %> 	
		<!-- we only reder the footer to include the javascript that makes google analytics runs -->

		</div> 
	</body>


</html>

app/views/legends/edit.html.erb
<div class="row">
	<div class="span8 offset2 centered">
		<div class="admin_form">

			<%= form_for(@legend) do |f| %> 
					<%= f.label :name %> 
					<%= f.text_field :name %>

					<%= f.label :description %> 
					<%= f.text_area :description %> 

					<%= f.label :image, "Image-Link" %> 			
					<%= f.text_field :image %>  <br> <br>

					<%= f.submit "Submit", class: "btn btn-medium btn-warning" %> 
			<% end %>

		</div>
	</div>
</div>

app/views/legends/index.html.erb
<div class="row"> 
	<div class="span10 offset1 centered"> 

		<h1> Content Mgmt Area :) </h1>
		<h2> <%= link_to "Add Legend", new_legend_path %> </h2>
		<h2> or manage existing ones: </h2> <br> <br>

		<% @legends.each do |legend| %> 

			<div class="box legend_box">
				<a href="<%= legend_books_path(legend) %>">	
				<img src= "<%= legend.image %>" width="300" height="300" /> </a> <br>  
				<h4> <%= link_to "Edit", edit_legend_path(legend) %> </h4>  
				<h4> <%= link_to 'Destroy', legend, method: :delete, data: { confirm: 'Delete this Legend?' } %> </h4>  
				<br>
			</div> 

		<% end %> 

	</div> 
</div> 

app/views/legends/new.html.erb
<div class="row">
	<div class="span8 offset2 centered"> 
		<div class="admin_form">

			<%= form_for(@legend) do |f| %> 

				<%= f.label :name %> 
				<%= f.text_field :name %>

				<%= f.label :description %> 
				<%= f.text_area :description, rows: 8 %> 

				<%= f.label :image, "Image-Link" %> 
				<%= f.text_field :image %> <br> <br>

				<%= f.submit "Submit", class: "btn btn-medium btn-warning" %> 

			<% end %>

		</div> 
	</div> 
</div> 

app/views/legends/show.html.erb
<% provide(:tab_title, "Booklist") %> 

<div class="row">
	<div class="span10 offset1 booklist">

		<div class="booklist_intro">
			<img src="<%= @legend.image %>" width="500" height="auto" /> 
			<h1> Books recommended by <%= @legend.name %> </h1> 
		</div> 
	
		
		<div class="booklist_body">
			<% @books.each do |book| %>
				<div class="book_picture">
					<a href="<%= book.link %>" target="_blank">
						<img src="<%= book.image %>" width="160" height="120" />  
					</a> <br>
					<a href="<%= book.link %>" target="_blank"> Amazon Link </a> 	
				</div>
				<div class="book_description">
					<a href="<%= book.link %>" target="_blank">
					<h3> <%= book.title %> </h3> </a> 
					<p> <%= book.description %> </p> 
				</div>
			<% end %> 
		</div> 

		<div class="booklist_side_bar">
			<h3> More reading <br> lists </h3> <br>
			<% @legends.each do |legend| %> 
			<p> <%= legend.name %> </p> 
			<a href="<%= legend_path(legend) %>"> 
				<img src="<%= legend.image %>" width="60%" height="auto" />  
			</a> 
			<% end %> <br> 
			<%= will_paginate :page_links => false %>
		</div> 
	
	</div> 
</div> 

app/views/static_pages/About.html.erb
<% provide(:tab_title, "About") %> 

<div class="row">
	<div class="span6 offset3 static_pages_box">

				<h1 class="centered"> Title </h1>	
			
				<p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p> 

	</div> 
</div> 

app/views/static_pages/Contact.html.erb
<% provide(:tab_title, "Contact") %> 

<div class="row">
	<div class="span6 offset3 static_pages_box">

				<h1 class="centered"> Title </h1>	
			
				<p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p> 

	</div> 
</div> 

app/views/static_pages/Home.html.erb
<% provide(:tab_title, "Home") %> 

<div class="slogan centered">
	<h1> Awesome Peoples' Reading Lists </h1> <br>	
	<h4> We have collected the reading list of some great people for you. Have fun exploring! </h4>
</div> 

<div id= "legends"> 
	<%= render 'layouts/legends' %> <br> 
</div> 

<%= will_paginate @legends %> 

			

app/views/static_pages/How.html.erb
<% provide(:tab_title, "How") %> 

<div class="row">
	<div class="span6 offset3 static_pages_box">

				<h1 class="centered"> Title </h1>	
			
				<p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p> 

	</div> 
</div> 

app/views/static_pages/Privacy.html.erb
<% provide(:tab_title, "Privacy") %> 

<div class="row">
	<div class="span6 offset3 static_pages_box">

				<h1 class="centered"> Title </h1>	
			
				<p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p> 

	</div> 
</div> 

app/views/static_pages/Terms.html.erb
<% provide(:tab_title, "Terms") %> 

<div class="row">
	<div class="span6 offset3 static_pages_box">

				<h1 class="centered"> Title </h1>	
			
				<p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p> 

	</div> 
</div> 

app/views/static_pages/user_email.html.erb
<% provide(:tab_title, "Suggestion") %> 

<div class="row">
	<div class="span6 offset3 user_email">

		<p> Dear user, <br> if you had an idea what other person to add to our list, please tell us below. Thank you! </p>

		<%= form_for(:email, url: emails_path) do |f| %> 
		<%= f.text_area :email, rows: 5, placeholder: "your suggestion..." %> <br>
		<%= f.submit "Tell us :)", class: "btn btn-medium btn-warning" %> 
		<% end %> 		

	</div> 
</div> 